In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch
# Imports
import torch.nn as nn

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
from torch.utils.data import TensorDataset


In [4]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[1:3]


(tensor([[ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 81., 101.],
         [119., 133.]]))

In [5]:
from torch.utils.data import DataLoader

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break


tensor([[102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[ 22.,  37.],
        [ 22.,  37.],
        [ 56.,  70.],
        [ 56.,  70.],
        [103., 119.]])


In [6]:
# Define model
model = nn.Linear(3, 2)
print("Weight : ",model.weight)
print("Bias : ",model.bias)


Weight :  Parameter containing:
tensor([[-0.2300,  0.4382,  0.1834],
        [-0.0500, -0.0263,  0.3144]], requires_grad=True)
Bias :  Parameter containing:
tensor([-0.2513, -0.1681], requires_grad=True)


In [7]:
# Parameters
list(model.parameters())


[Parameter containing:
 tensor([[-0.2300,  0.4382,  0.1834],
         [-0.0500, -0.0263,  0.3144]], requires_grad=True),
 Parameter containing:
 tensor([-0.2513, -0.1681], requires_grad=True)]

In [8]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)



In [9]:
# Import nn.functional
import torch.nn.functional as F

# Define loss function
loss_fn = F.mse_loss


In [10]:
loss = loss_fn(model(inputs), targets)
print("Loss : ",loss)


Loss :  tensor(5169.1924, grad_fn=<MseLossBackward0>)


In [11]:
# train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [12]:
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)


Epoch [10/100], Loss: 93.7045
Epoch [20/100], Loss: 84.6219
Epoch [30/100], Loss: 34.2424
Epoch [40/100], Loss: 101.5253
Epoch [50/100], Loss: 59.8792
Epoch [60/100], Loss: 13.3523
Epoch [70/100], Loss: 22.2071
Epoch [80/100], Loss: 18.1896
Epoch [90/100], Loss: 8.5853
Epoch [100/100], Loss: 11.4914


In [13]:
# Generate predictions
preds = model(inputs)
preds


tensor([[ 57.8676,  71.3752],
        [ 80.8710,  99.8513],
        [120.7983, 133.2501],
        [ 25.0693,  43.1049],
        [ 97.2056, 114.1163],
        [ 57.8676,  71.3752],
        [ 80.8710,  99.8513],
        [120.7983, 133.2501],
        [ 25.0693,  43.1049],
        [ 97.2056, 114.1163],
        [ 57.8676,  71.3752],
        [ 80.8710,  99.8513],
        [120.7983, 133.2501],
        [ 25.0693,  43.1049],
        [ 97.2056, 114.1163]], grad_fn=<AddmmBackward0>)

In [14]:
# Compare with targets
targets


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [15]:
fit(100, model, loss_fn, opt)


Epoch [10/100], Loss: 8.6881
Epoch [20/100], Loss: 12.8765
Epoch [30/100], Loss: 10.8653
Epoch [40/100], Loss: 6.1459
Epoch [50/100], Loss: 5.5342
Epoch [60/100], Loss: 6.7127
Epoch [70/100], Loss: 3.2619
Epoch [80/100], Loss: 4.9362
Epoch [90/100], Loss: 7.0426
Epoch [100/100], Loss: 3.8241
