In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [3]:
# Target (apples)
targets = np.array(
[[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [5]:
# Weights and biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.8861,  0.9223, -0.5837]], requires_grad=True)
tensor([-0.3439,  0.2453], requires_grad=True)


In [6]:
# Define the model
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[101.0423, 101.6315],
        [124.1048, 124.6941],
        [166.4899, 167.0792],
        [108.1053, 108.6946],
        [108.4871, 109.0764]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(2744.2246, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print("Gradients for weights")
print(w)
print(w.grad)

# Gradients for bias
print("\nGradients for bias")
print(b)
print(b.grad)

Gradients for weights
tensor([[ 0.8861,  0.9223, -0.5837]], requires_grad=True)
tensor([[8251.1729, 7012.0396, 4440.0303]])

Gradients for bias
tensor([-0.3439,  0.2453], requires_grad=True)
tensor([45.4459, 46.0351])


In [13]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.]])
tensor([0., 0.])


In [14]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[101.0423, 101.6315],
        [124.1048, 124.6941],
        [166.4899, 167.0792],
        [108.1053, 108.6946],
        [108.4871, 109.0764]], grad_fn=<AddBackward0>)


In [15]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(2744.2246, grad_fn=<DivBackward0>)


In [16]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[8251.1729, 7012.0396, 4440.0303]])
tensor([45.4459, 46.0351])


In [17]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)
print(b)

tensor([[ 0.8036,  0.8522, -0.6281]], requires_grad=True)
tensor([-0.3444,  0.2449], requires_grad=True)


In [18]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1616.8307, grad_fn=<DivBackward0>)


In [19]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [20]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(187.6240, grad_fn=<DivBackward0>)


In [21]:
# Predictions
preds

tensor([[ 60.0577,  60.6464],
        [ 75.3729,  75.9616],
        [128.1484, 128.7371],
        [ 38.4851,  39.0738],
        [ 79.9111,  80.4997]], grad_fn=<AddBackward0>)

In [22]:
# Targets
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])