In [ ]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
import math

In [ ]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer (3).csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
transformed_data = sc.fit_transform(data)

In [ ]:
transformed_data

array([[-1.78179743, -1.49004624, -0.74593581],
       [-0.25358736, -1.46068138, -0.74593581],
       [-1.11320552, -0.78528968, -0.74593581],
       ...,
       [ 1.17910958, -1.46068138,  1.34059793],
       [-0.15807423, -1.07893824, -0.74593581],
       [ 1.08359645, -0.99084367,  1.34059793]])

In [ ]:
X = transformed_data[:,0:2]
Y = transformed_data[:,2]

In [ ]:
Y = [0 if a<0 else 1 for a in Y]
Y = np.array(Y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 47)

In [ ]:
class LogisticRegression:
  def sigmoid(self,X):
    return 1/(1+np.exp(-((X).dot(self.Weights)+self.Bias)))
  
  def __init__(self,lr,epochs=100):
    self.learning_rate = lr
    self.epochs = epochs
    pass
  
  def get_loss(self):
    return (np.sum(-1*(self.Y)*np.log(self.sigmoid(self.X))-(1-self.Y)*np.log(1-self.sigmoid(self.X)))/self.Num_samples)
  
  def fit(self,X,Y):
    
    # Assigning data to X and Y
    self.X = X
    self.Y = Y

    # Computing M -> No of training samples 
    # Computing N -> No of features
    self.Num_samples,self.Num_features = X.shape
    print(self.Num_samples,self.Num_features)

    # Initializing all the weights
    self.Weights = np.zeros(self.Num_features)
    self.Bias = 0
    for i in range(self.epochs):
      print("Epoch ",i)
      self.run_optimization()
      print(self.get_loss())
    return self
  
  # Return predictions based on X
  def predict(self,X):
    ret_val = []
    for dat in self.sigmoid(X):
      ret_val.append(1 if dat>=0.5 else 0)
    return ret_val


  def run_optimization(self):
    # Gradient Calculation
    ans = self.sigmoid(self.X)
    t = ( ans - self.Y.T )
    t = np.reshape( t, self.Num_samples ) 

    dW = np.dot( self.X.T, t ) / self.Num_samples
    db = np.sum( t ) / self.Num_samples
    

    self.Weights = self.Weights - self.learning_rate * dW    
    self.Bias = self.Bias - self.learning_rate * db
           



    

In [ ]:
lr = LogisticRegression(0.1,400)
lr.fit(X_train,y_train)

320 2
Epoch  0
0.6798748604741558
Epoch  1
0.6673323217894069
Epoch  2
0.6554777689103317
Epoch  3
0.6442708455001981
Epoch  4
0.6336728146367505
Epoch  5
0.623646684745252
Epoch  6
0.6141572883174874
Epoch  7
0.6051713205633391
Epoch  8
0.5966573449106123
Epoch  9
0.5885857717851668
Epoch  10
0.580928816466029
Epoch  11
0.5736604410979073
Epoch  12
0.5667562852155124
Epoch  13
0.5601935884316173
Epoch  14
0.5539511082904066
Epoch  15
0.5480090357042753
Epoch  16
0.5423489098821243
Epoch  17
0.5369535342206199
Epoch  18
0.5318068942631378
Epoch  19
0.526894078528182
Epoch  20
0.5222012027627673
Epoch  21
0.5177153379790644
Epoch  22
0.5134244424772121
Epoch  23
0.5093172979367839
Epoch  24
0.5053834495678757
Epoch  25
0.5016131502447793
Epoch  26
0.49799730849615553
Epoch  27
0.49452744019163386
Epoch  28
0.49119562374261144
Epoch  29
0.4879944586220574
Epoch  30
0.4849170270021764
Epoch  31
0.4819568583081054
Epoch  32
0.47910789648902263
Epoch  33
0.47636446981402825
Epoch  34
0.4737

In [ ]:
lr.Weights

array([1.98150792, 0.94555763])

In [ ]:
def getScore(y_originals,y_pred):
  true = 0
  false = 0
  for i in range(len(y_pred)):
    if y_pred[i]==y_originals[i]:
      true = true + 1
    else:
      false = false + 1
  return true/(true+false)

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
getScore(y_test,y_pred)*100

91.25

In [ ]:
y_test

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
np.array(y_pred)

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0])