In [6]:
import numpy as np

In [3]:
#Create a Numpy array of size 4 x 5
arr=np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4]])
print("Numpy array of size 4 x 5 is:\n",arr)

Numpy array of size 4 x 5 is:
 [[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [4]:
#Randomly initialize the array.
rand_init1=np.random.randint(1,50,size=(4,5))
print("Randomly initialized array of size 4x5 is:\n",rand_init1)

Randomly initialized array of size 4x5 is:
 [[30 10 19 19 49]
 [31  2 15 30 41]
 [39 30 42 22  2]
 [20  7 24 44  5]]


In [5]:
#Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant
print("Transpose of matrix is:\n",arr.T)
square_matrix=np.array([[1,2],[3,4]])
print("Square matrix is:\n",square_matrix)
print("Square matrix's determinant is:\n",int(np.linalg.det(square_matrix)))

Transpose of matrix is:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
Square matrix is:
 [[1 2]
 [3 4]]
Square matrix's determinant is:
 -2


In [7]:
# Create another matrix of size 5 x 4 and randomly initialize it
rand_init2=np.random.randint(1,50,size=(5,4))
print("Randomly initialized array of size 5x4 is:\n",rand_init2)

Randomly initialized array of size 5x4 is:
 [[40 31  4 14]
 [17 19 30  5]
 [25 27  5 45]
 [27  5  7 12]
 [44  6 30 33]]


In [8]:
#Perform Matrix multiplication
print("Matrix multiplication is:\n",np.dot(rand_init1,rand_init2))

Matrix multiplication is:
 [[4514 2022 2118 3170]
 [4263 1800 1699 2832]
 [3802 3035 1480 2916]
 [2927 1651  868 2088]]


In [9]:
#Perform element wise matrix multiplication
print("Element wise matrix multiplication of size 4x5 is:\n",rand_init1*rand_init1)
print("Element wise matrix multiplication of size 5x4 is:\n",rand_init1*rand_init1)

Element wise matrix multiplication of size 4x5 is:
 [[ 900  100  361  361 2401]
 [ 961    4  225  900 1681]
 [1521  900 1764  484    4]
 [ 400   49  576 1936   25]]
Element wise matrix multiplication of size 5x4 is:
 [[ 900  100  361  361 2401]
 [ 961    4  225  900 1681]
 [1521  900 1764  484    4]
 [ 400   49  576 1936   25]]


In [10]:
# Find mean, median of the numpy array created.
print("Mean of numpy array is:",np.mean(arr))
print("Median of numpy array is:",np.median(arr))

Mean of numpy array is: 2.5
Median of numpy array is: 2.5


In [11]:
#  Obtain each row in the second column of the first array
print("Obtain each row in the second column of the first array is:",arr[:,1])

Obtain each row in the second column of the first array is: [1 2 3 4]


In [28]:
# Convert Numeric entries(columns) of Iris.csv to Mean Centered Version
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
data=pd.read_csv('/content/sample_data/Iris.csv')
arr=data.values[:,:5]
# print(arr)
# print(np.mean(arr, axis=0))
nparrayCentered = arr - np.mean(arr, axis=0) 
print(nparrayCentered)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[-74.5 -0.743333333333335 0.4459999999999993 -2.3586666666666694
  -0.9986666666666673]
 [-73.5 -0.9433333333333342 -0.054000000000000714 -2.3586666666666694
  -0.9986666666666673]
 [-72.5 -1.1433333333333344 0.14599999999999946 -2.4586666666666694
  -0.9986666666666673]
 [-71.5 -1.243333333333335 0.045999999999999375 -2.2586666666666693
  -0.9986666666666673]
 [-70.5 -0.8433333333333346 0.5459999999999994 -2.3586666666666694
  -0.9986666666666673]
 [-69.5 -0.44333333333333425 0.8459999999999992 -2.058666666666669
  -0.7986666666666672]
 [-68.5 -1.243333333333335 0.3459999999999992 -2.3586666666666694
  -0.8986666666666672]
 [-67.5 -0.8433333333333346 0.3459999999999992 -2.2586666666666693
  -0.9986666666666673]
 [-66.5 -1.4433333333333342 -0.1540000000000008 -2.3586666666666694
  -0.9986666666666673]
 [-65.5 -0.9433333333333342 0.045999999999999375 -2.25866

In [12]:
# Study about numpy array attributes and implement it on the first matrix
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.T)
print(arr.itemsize)

2
(4, 5)
20
int64
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
8
